# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mlamkadm <mlamkadm@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/13 16:46:59 by mlamkadm          #+#    #+#              #
#    Updated: 2025/01/13 16:46:59 by mlamkadm         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

services:
  nginx:

  maria-db:

  backend:
    #php+wordpress
