# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mlamkadm <mlamkadm@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/03/02 00:17:34 by mlamkadm          #+#    #+#              #
#    Updated: 2025/03/02 01:17:49 by mlamkadm         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception-42
    ports:
      - "4443:443"
    # depends_on:
      # wordpress:
      #   condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:443", "-k", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  maria-db:
    container_name: maria-db
    image: maria-db
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASS}
      - WORDPRESS_DB_NAME=${WP_DB_NAME}
      - WORDPRESS_USER=${WP_USER}
      - WORDPRESS_PASSWORD=${WP_PASS}
    networks:
      - inception-42
    ports:
      - ":3306"
    volumes:
      - maria-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--user=${WP_USER}", "--password=${WP_PASS}"]
      interval: 20s
      timeout: 15s
      retries: 3
      start_period: 10s 
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    environment:
      - WORDPRESS_DB_NAME=${WP_DB_NAME}
      - WORDPRESS_USER=${WP_USER}
      - WORDPRESS_PASSWORD=${WP_PASS}

      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_URL=${WP_URL}
      - WP_TITLE=${WP_TITLE}
    ports:
      - "9000:9000"
    networks:
      - inception-42
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      maria-db:
        condition: service_healthy
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "cgi-fcgi", "-bind", "-connect", "localhost:9000"]
    #   interval: 20s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s

volumes:
  maria-db:
    name: db
  wordpress:
    name: wp

networks:
  inception-42:
    name: inception-network
