# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mlamkadm <mlamkadm@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/13 16:46:59 by mlamkadm          #+#    #+#              #
#    Updated: 2025/03/01 05:58:50 by mlamkadm         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception-42
    ports:
      - "4443:443"
    depends_on:
      - wordpress
    restart: unless-stopped

  maria-db:
    container_name: maria-db
    image: maria-db
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASS}
      - WORDPRESS_DB_NAME=${WP_DB_NAME}
      - WORDPRESS_USER=${WP_USER}
      - WORDPRESS_PASSWORD=${WP_PASS}
    networks:
      - inception-42
    ports:
      - ":3306"
    volumes:
      - maria-db:/var/lib/mysql
    # healthcheck:
    # implement in the future for orchestration.
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    environment:
      - WORDPRESS_DB_NAME=${WP_DB_NAME}
      - WORDPRESS_USER=${WP_USER}
      - WORDPRESS_PASSWORD=${WP_PASS}

      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_URL=${WP_URL}
      - WP_TITLE=${WP_TITLE}
    ports:
      - "9000:9000"
    networks:
      - inception-42
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - maria-db
    restart: unless-stopped

volumes:
  maria-db:
    name: db
  wordpress:
    name: wp

networks:
  inception-42:
    name: inception-network
    

