# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mlamkadm <mlamkadm@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/13 16:46:59 by mlamkadm          #+#    #+#              #
#    Updated: 2025/01/13 16:46:59 by mlamkadm         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    ports:
      - "443:9000"
    # depends_on:
    #   - backend

  maria-db:
    container_name: maria-db
    image: maria-db
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    ports:
      - ":3306"
    # volumes:
    #   - data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  # backend:
  #   build:
  #     context: .
  #     dockerfile: requirements/wordpress/Dockerfile
  #   volumes:
  #     - wordpress-data:/var/www/html
  #   environment:
  #     WORDPRESS_DB_HOST: maria-db
  #     WORDPRESS_DB_USER: wordpress
  #     WORDPRESS_DB_PASSWORD: wordpress
  #     WORDPRESS_DB_NAME: wordpress
  #   depends_on:
  #     - maria-db

# volumes:
#   :/data/
  # wordpress-data:
