# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mlamkadm <mlamkadm@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/13 16:46:59 by mlamkadm          #+#    #+#              #
#    Updated: 2025/01/13 16:46:59 by mlamkadm         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


services:
  # nginx:
  #   build:
  #     context: .
  #     dockerfile: nginx/Dockerfile

  maria-db:
    build:
      context: .
      dockerfile: /mariadb/Dockerfile
    ports:
      - :3306
    volumes:
      - /db-data:/db-data

  # backend:
  #   build:
  #     context: .
  #     dockerfile: ./requirements/wordpress/Dockerfile
  #   healthcheck:
  #     test: ["CMD", "echo", "healthcheck"]
  #     interval: 10s
  #     timeout: 3s
  #     retries: 3 
    #php+wordpress


# volumes:
  # db-data:
  # wordpress:
