# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yml                                 :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mlamkadm <mlamkadm@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/03/08 14:47:11 by mlamkadm          #+#    #+#              #
#    Updated: 2025/03/08 14:47:11 by mlamkadm         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# ======================================================================================
# STACK
# ======================================================================================

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:lbro
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception-42
    ports:
      - "443:443"
    depends_on:
      wordpress:
        condition: service_started
    restart: always

  maria-db:
    container_name: maria-db
    image: mariadb:lbro
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASS}
      - WORDPRESS_DB_NAME=${WP_DB_NAME}
      - WORDPRESS_USER=${WP_USER}
      - WORDPRESS_PASSWORD=${WP_PASS}
    networks:
      - inception-42
    ports:
      - ":3306"
    volumes:
      - maria-db:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 3
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress:lbro
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    environment:
      - WORDPRESS_DB_HOST=${DB_HOST}
      - WORDPRESS_DB_NAME=${WP_DB_NAME}
      - WORDPRESS_USER=${WP_USER}
      - WORDPRESS_PASSWORD=${WP_PASS}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASS=${WP_ADMIN_PASS}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_URL=${WP_URL}
      - EXTRA_USERNAME=${EXTRA_USERNAME}
      - EXTRA_EMAIL=${EXTRA_EMAIL}
      - EXTRA_PASS=${EXTRA_PASS}
      - EXTRA_ROLE=${EXTRA_ROLE}
    networks:
      - inception-42
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      maria-db:
        condition: service_healthy
    restart: always

# ======================================================================================
# VOLUMES
# ======================================================================================

volumes:
  maria-db:
    name: maria-db-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/maria-db

  wordpress:
    name: wordpress-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

# ======================================================================================
# NETWORKS
# ======================================================================================

networks:
  inception-42:
    name: inception-network
    driver: bridge
